# Generated by Django 6.0.5 on 2026-10-05 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0019_propertyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team')], default='personal', max_length=10)),
                ('track', models.CharField(choices=[('agent', 'Agent'), ('owner', 'Owner')], default='owner', max_length=10)),
                ('country', models.CharField(default='NG', max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_country', models.CharField(blank=True, max_length=2, null=True)),
                ('billing_entity', models.CharField(blank=True, max_length=120, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('brand_color', models.CharField(default='#10b981', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unsubmitted', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('agent', 'Agent'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='owner', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='workspaces__user_id_bbd448_idx')],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PropertyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='manager', max_length=20)),
                ('can_list', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_memberships', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('agent_free', 'Agent Free'), ('agent_starter', 'Agent Starter'), ('agent_pro', 'Agent Pro'), ('agent_agency', 'Agent Agency'), ('agent_enterprise', 'Agent Enterprise'), ('owner_free', 'Owner Free'), ('owner_starter', 'Owner Starter'), ('owner_pro', 'Owner Pro'), ('owner_agency', 'Owner Agency'), ('owner_enterprise', 'Owner Enterprise')], default='owner_free', max_length=20)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], default='month', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('limit_overrides', models.JSONField(blank=True, default=dict)),
                ('billing_country', models.CharField(blank=True, max_length=2, null=True)),
                ('paddle_customer_id', models.CharField(blank=True, max_length=255)),
                ('paddle_subscription_id', models.CharField(blank=True, max_length=255)),
                ('paddle_price_id', models.CharField(blank=True, max_length=255)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='workspaces.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['paddle_subscription_id'], name='workspaces__paddle__a8c865_idx')],
            },
        ),
    ]
