# Generated by Django 6.0.5 on 2026-10-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_backfill_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
