# Generated by Django 6.0.5 on 2026-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_organization_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_entity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('agent_free', 'Agent Free'), ('agent_starter', 'Agent Starter'), ('agent_pro', 'Agent Pro'), ('agent_agency', 'Agent Agency'), ('owner_free', 'Owner Free'), ('owner_starter', 'Owner Starter'), ('owner_pro', 'Owner Pro'), ('owner_enterprise', 'Owner Enterprise')], default='owner_free', max_length=20),
        ),
    ]
