# Generated by Django 6.0.5 on 2026-05-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_payment_reference_alter_maintenancerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
