# Generated by Django 6.0.5 on 2026-05-23 04:02

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_tenant_data(apps, schema_editor):
    Tenant = apps.get_model('properties', 'Tenant')
    for tenant in Tenant.objects.all():
        tenant.annual_rent = tenant.monthly_rent
        tenant.tenancy_status = 'active'
        tenant.save()


def copy_payment_data(apps, schema_editor):
    Payment = apps.get_model('properties', 'Payment')
    import re
    from calendar import monthrange
    from datetime import datetime
    months_map = {
        'january': 1, 'february': 2, 'march': 3, 'april': 4,
        'may': 5, 'june': 6, 'july': 7, 'august': 8,
        'september': 9, 'october': 10, 'november': 11, 'december': 12,
        'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4,
        'jun': 6, 'jul': 7, 'aug': 8, 'sep': 9,
        'oct': 10, 'nov': 11, 'dec': 12,
    }
    for payment in Payment.objects.all():
        m = re.match(r'(\w+)\s+(\d{4})', payment.month_for or '')
        if m:
            month_name = m.group(1).strip().lower()
            year = int(m.group(2))
            month_num = months_map.get(month_name)
            if month_num:
                _, last_day = monthrange(year, month_num)
                payment.period_start = datetime(year, month_num, 1).date()
                payment.period_end = datetime(year, month_num, last_day).date()
                payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='years_covered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='annual_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenancy_status',
            field=models.CharField(choices=[('pending_document', 'Pending Document'), ('document_sent', 'Document Sent'), ('document_signed', 'Document Signed'), ('active', 'Active'), ('expired', 'Expired'), ('quit_notice_issued', 'Quit Notice Issued')], default='pending_document', max_length=20),
        ),
        migrations.CreateModel(
            name='QuitNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField(default=datetime.date.today)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('enforced', 'Enforced'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quit_notices', to='properties.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('reminder_type', models.CharField(choices=[('lease_expiry', 'Lease Expiry'), ('rent_due', 'Rent Due'), ('quit_notice', 'Quit Notice'), ('document_sign', 'Document Sign')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('message', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='properties.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenancyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='tenancy_agreement', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('document_data', models.JSONField(default=dict)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('signed_file_url', models.URLField(blank=True, null=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.tenant')),
            ],
        ),
        migrations.RunPython(copy_tenant_data, migrations.RunPython.noop),
        migrations.RunPython(copy_payment_data, migrations.RunPython.noop),
    ]
