# Generated by Django 6.0.5 on 2026-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20260523_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
