# Generated by Django 6.0.5 on 2026-06-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_payment_approved_at_payment_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenancyAgreementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tenancy Agreement', max_length=200)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('template_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_template', to='properties.property')),
            ],
        ),
    ]
