# Generated by Django 6.0.5 on 2026-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_tenancyagreementtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancyagreementtemplate',
            name='mode',
            field=models.CharField(choices=[('template', 'Use Agreement Template'), ('uploaded_pdf', 'Upload Scanned PDF')], default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='tenancyagreementtemplate',
            name='uploaded_pdf_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenancydocument',
            name='mode',
            field=models.CharField(choices=[('template', 'Template'), ('uploaded_pdf', 'Uploaded PDF')], default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='tenancydocument',
            name='verification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenancydocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('completed', 'Completed'), ('pending_verification', 'Pending Verification')], default='draft', max_length=20),
        ),
    ]
