# Generated by Django 6.0.5 on 2026-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_tenancyagreementtemplate_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rent_cycle',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='rent_cycle',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10),
        ),
    ]
