# Generated by Django 6.0.5 on 2026-06-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_slug',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
