# Generated by Django 6.0.5 on 2026-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_backfill_public_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancydocument',
            name='unsigned_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
