# Generated by Django 6.0.5 on 2026-09-03 09:33

import uuid
from django.db import migrations, models


def backfill_slugs(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for prop in Property.objects.all():
        if not prop.public_slug:
            prop.public_slug = uuid.uuid4().hex[:12]
            prop.save(update_fields=['public_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_tenancydocument_unsigned_emailed_at'),
    ]

    operations = [
        # Step 1: Add field as nullable (no unique constraint yet)
        migrations.AddField(
            model_name='property',
            name='public_slug',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        # Step 2: Backfill with unique slugs
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # Step 3: Now make it unique and non-nullable
        migrations.AlterField(
            model_name='property',
            name='public_slug',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
