# Generated by Django 6.0.5 on 2026-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_public_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='public_slug',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
