# Generated by Django 6.0.5 on 2026-09-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_notification_type_propertyavailability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='', max_length=500)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('page_path', models.CharField(blank=True, default='', max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='properties.property')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['property', 'viewed_at'], name='properties__propert_477678_idx'), models.Index(fields=['utm_source'], name='properties__utm_sou_048db8_idx')],
            },
        ),
    ]
